core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [

    path("", include('pwa.urls')),

    path('admin/', admin.site.urls),
    path("", include('generales.urls')),

    path("usuarios/", include('usuarios.urls')),
    path("paciente/", include('paciente.urls')),
    
    path("agenda/", include('agenda.urls'), name='Agenda'),
    path("clinicas/", include('clinicas.urls')),

    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),

    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from clinicas.models import Clinica
# Create your models here.
from django.conf import settings

from django.utils.translation import gettext_lazy as _



class Idiomas(models.Model):
    IDIOMAS = [
        ('Aleman', 'Aleman'),
        ('Español', 'Español'),
        ('Ingles', 'Ingles'),
        ('Italiano', 'Italiano'),
        ('Portugues', 'Portugues')
    ]

    idoma = models.CharField(choices= IDIOMAS, max_length=50, null=True)

class CustomUser(AbstractUser):
    TIPOS_USUARIO = (
        ('administrador', 'Administrador'),
        ('dentista', 'Dentista'),
        ('asistente', 'Asistente'),
        ('paciente', 'Paciente'),
        ('responsable', 'Responsable')
    )
    apellido_materno = models.CharField(max_length=100, blank=True)
    direccion = models.CharField(max_length=255, blank=True)
    celular = models.CharField(max_length=20, blank=True)
    telefono_fijo = models.CharField(max_length=20, blank=True)
    email = models.EmailField(_('email address'), unique=True)

    tipo_usuario = models.CharField(choices=TIPOS_USUARIO, max_length=15)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    numero = models.CharField(max_length=15, null=True, blank=True, verbose_name='No. celular')
    foto = models.ImageField(upload_to='usuarios/fotos/', null=True, blank=True)
    clinicas = models.ManyToManyField(Clinica, related_name='usuarios_asignados')
    idiomas = models.ManyToManyField(Idiomas, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='created_users',
        verbose_name='Creado por'
    )

    def contar_clinicas_asignadas(self):
        if self.tipo_usuario == 'responsable':
            return self.clinicas.count()
        else:
            return 0
        
    IDIOMAS= (
        ('español' , 'Español'),
        ('inglés' , 'Inglés'),
        ('francés', 'Francés'),
        ('aleman', 'Alemán')
    )
    idiomas = models.CharField(max_length=255, choices = IDIOMAS, null=True, blank=True, verbose_name='Idiomas hablados')

    SEX_CHOICES = [
        ('Hombre', 'Hombre'),
        ('Mujer', 'Mujer'),
        # Puedes agregar más opciones si es necesario
    ]
    sexo = models.CharField(max_length=10, choices=SEX_CHOICES, blank=True, verbose_name='Genero')
    fecha_nacimiento = models.DateField(null=True, blank=True, verbose_name='Fecha de nacimiento')

    PREGUNTAS_SEGURIDAD_1 = [
        ('nombre_primera_mascota', '¿Cuál es el nombre de tu primera mascota?'),
        ('ciudad_nacimiento', '¿En qué ciudad naciste?'),
        ('nombre_mejor_amigo', '¿Cómo se llama tu mejor amigo de la infancia?'),
    ]

    PREGUNTAS_SEGURIDAD_2 = [
        ('primer_coche', '¿Cuál fue la marca de tu primer coche?'),
        ('primera_escuela', '¿Cómo se llama tu primera escuela?'),
        ('plato_favorito', '¿Cuál es tu plato favorito?'),
    ]

    pregunta_seguridad_1 = models.CharField(max_length=255, choices=PREGUNTAS_SEGURIDAD_1, blank=True, null=True)
    respuesta_seguridad_1 = models.CharField(max_length=255, blank=True,  null=True)
    pregunta_seguridad_2 = models.CharField(max_length=255, choices=PREGUNTAS_SEGURIDAD_2, blank=True, null=True)
    respuesta_seguridad_2 = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        # Construye el nombre completo
        nombre_completo = f"{self.first_name.title()} {self.last_name.title()} {self.apellido_materno.title()}".strip()
        if self.clinicas:
            nombre_completo += f" - Clínica: {self.clinicas}"
        return nombre_completo if nombre_completo else self.username
        
class AsistenteDentista(models.Model):
    asistente = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='asistente_dentistas')
    dentista = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='dentista_asistentes')

    def __str__(self):
        return f"{self.asistente.username} asiste a {self.dentista.username}"

class Administrador(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    dato_especifico_admin = models.CharField(max_length=255)



class Medico(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    cedula_profesional = models.CharField(max_length=255)
    

class Asistente(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    dato_especifico_asistente = models.CharField(max_length=255)

class Paciente(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    dato_especifico_paciente = models.CharField(max_length=255)

core/dentistas/templates/listDentistas.html
{% extends "general/base.html" %}
{% load static %}
{% block titulo %}
Ver Pacientes
{% endblock titulo %}
{% block link%}
    <link rel="stylesheet" href="{% static "plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/datatables-responsive/css/responsive.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/datatables-buttons/css/buttons.bootstrap4.min.css" %}">
{% endblock link %}


{% block dashboard %}


<a class="btn btn-sm  " href="{% url "home" %}">      
      <button class="btn-custom">
        <i class="fas fa-chevron-left"></i>
      </button>  
</a>
{% endblock dashboard %}


{% block contenido %}

<style>
    #example {
        border-collapse: separate;
        border-spacing: 0 10px;
        width: 100%;
        border: none;
    }

    #example thead tr {
        background-color: #007bff; /* Cambia este color según tu preferencia */
        color: white;
    }

    #example th, #example td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
        vertical-align: middle;
    }

    #example tr:nth-child(even) {background-color: #f2f2f2;}

    #example tr:hover {background-color: #ddd;}

    .user-picture-medium {
        border-radius: 50%;
        width: 50px;
        height: 50px;
    }


    #example thead tr {
        background-color: #4C9BB6;
        color: white;
        border-radius: 100%;
    }
</style>





<div class="card card1">
    <div class="card-header">
        <i class="fas fa-person fa-2x" style="color: #239db9;"></i> <strong>Lista de Dentistas </strong>
    </div>
    <div class="card-body">
       {% if grupo_dentista_existe %}

        {% else %}
            <a href="{% url "register_user_dentista" %}" class="btn btn-custom2">Agregar nuevo dentista</a>

        {% endif %}
        
        <table id="example" class="display" style="width:100%">
            <thead>
                <tr>
                    <th></th>
        

                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Teléfono</th>
                    <th>Tipo Usuario</th>

                </tr>
            </thead>
            <tbody>
                {% for paciente in dentistas %}
                <tr>

                    {% if paciente.foto  %}
                    <td style="text-align: center; vertical-align: middle;">

                        <img src="{{paciente.foto.url }}" class="img-circle elevation-2  user-picture-medium mt-2 " alt="User Image">
                        <br>
                    </td>
                    
                    {% else %}
                    <td style="text-align: center; vertical-align: middle;">
                            {% if paciente.sexo == "Hombre" %}
                                    <img src="{% static 'img/users/user_male.png' %}" class="img-circle elevation-2 user-picture user-picture-medium" alt="User Image">
                            {% elif paciente.sexo == "Mujer" %}
                                    <img src="{% static 'img/users/user_female.png' %}" class="img-circle elevation-2 user-picture user-picture-medium" alt="User Image">
                            {% else %}
                                    <img src="{% static 'img/usuariono.png' %}" class="img-circle elevation-2 user-picture user-picture-medium" alt="User Image">

                            {% endif %}

                        </td>
                    {% endif %}

                    <td>{{ paciente.get_full_name }}</td>
                    <td>{{ paciente.email }}</td>
                    <td>{{ paciente.celular }}</td>
                    <td>{{ paciente.get_tipo_usuario_display }}</td>

                    <!-- Más campos de paciente si es necesario -->
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No hay pacientes registrados.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        

    </div>
</div>
</div>









{% endblock contenido %}

{% block script1 %}
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "dist/js/adminlte.min.js" %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>

<script>
  $(document).ready(function() {
    // Define la configuración de DataTables dentro de la función ready para asegurarte de que el DOM está cargado.
    $("#example").DataTable({
      {% block filtro %}
      // Aquí podrías incluir cualquier filtro personalizado si es necesario.
      {% endblock filtro %}
      paging: true,
      responsive: true,
      lengthMenu: [5, 10, 25, 50, 100],
      pageLength: 5,
      lengthChange: false,
      autoWidth: false,
      searching: true,
      bInfo: true,
      bSort: true,
      {% block dom %}
      // La 'f' delante de 'B' asegura que el buscador se coloque primero.
      dom: 'fBrtlip',
      {% endblock dom %}
      buttons: [
        {
          text: 'Nuevo Dentista',
          className: 'btn btn-custom2 mr-2',
          action: function (e, dt, node, config) {
            window.location.href = '{% url "register_user_dentista" %}';
          }
        },

        // Botones por defecto
        {extend: 'copy', text: '<i class="fas fa-clone"></i>', class: 'btn btn-secondary', titleAttr: 'Copiar a Documento', exportOptions: {  columns: ':visible'  }},
        {extend: 'excel', text: '<i class="fas fa-file-excel"></i>', class: 'btn btn-secondary', titleAttr: 'Exportar a Excel', exportOptions: {  columns: ':visible' }},
        {extend: 'print', text: '<i class="fas fa-print"></i>', class: 'btn btn-secondary', titleAttr: 'Imprimir', exportOptions: {  columns: ':visible'  }},
        {extend: 'colvis', text: '<i class="fas fa-switch"></i>', class: 'btn btn-secondary', titleAttr: 'Imprimir', exportOptions: { columns: ':visible'  }},
        {% block datatable %}
        // Aquí puedes definir botones personalizados si es necesario.
        {% endblock datatable %}
        {% block datatable2 %}
        // Estos son los botones por defecto que se añadirán al DataTables.
        {% endblock datatable2 %}
      ],
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sSearch": "Buscar:",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "Primero",
            "sLast": "Último",
            "sNext": "Siguiente",
            "sPrevious": "Anterior"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        },
        "buttons": {
            "copy": "Copiar",
            "colvis": "Visibilidad"
        }
      }
    });
    $("#example_wrapper .btn").css("margin-bottom", "40px"); // Ajusta el margen según tus necesidades
    $("#example_info").css("margin-bottom", "40px"); // Ajusta el margen según tus necesidades

    
  });




</script>

{% endblock script1 %}